"""Initial migration

Revision ID: 6b4b113de0f6
Revises: 
Create Date: 2024-11-29 11:40:51.095638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4b113de0f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_historical_data_date', table_name='historical_data')
    op.drop_index('ix_historical_data_id', table_name='historical_data')
    op.drop_table('historical_data')
    op.add_column('miners', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('miners', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('miners', 'release_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('miners', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('miners', sa.Column('status', sa.VARCHAR(), nullable=True))
    op.alter_column('miners', 'release_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('miners', 'updated_at')
    op.drop_column('miners', 'created_at')
    op.create_table('historical_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('btc_price', sa.FLOAT(), nullable=True),
    sa.Column('network_difficulty', sa.FLOAT(), nullable=True),
    sa.Column('hashprice', sa.FLOAT(), nullable=True),
    sa.Column('network_hashrate', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_data_id', 'historical_data', ['id'], unique=False)
    op.create_index('ix_historical_data_date', 'historical_data', ['date'], unique=False)
    # ### end Alembic commands ###
